import { createClient } from '@supabase/supabase-js';
import dotenv from 'dotenv';
import path from 'path';

// Load environment variables
const envPath = path.resolve(__dirname, '../.env');
console.log('Loading .env from:', envPath);
dotenv.config({ path: envPath });

// Fallback to default if not found
if (!process.env.SUPABASE_URL) {
  console.log('Trying default .env location...');
  dotenv.config();
}

console.log('SUPABASE_URL:', process.env.SUPABASE_URL ? 'Found' : 'Missing');
console.log('SUPABASE_KEY:', (process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.SUPABASE_ANON_KEY) ? 'Found' : 'Missing');

const supabaseUrl = process.env.SUPABASE_URL || '';
const supabaseKey = process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.SUPABASE_ANON_KEY || '';

if (!supabaseUrl || !supabaseKey) {
  console.error('Missing Supabase credentials in .env');
  process.exit(1);
}

const supabase = createClient(supabaseUrl, supabaseKey);

const initialCareerData = [
  { name: 'Bronze', cycles: 5, min_lines: 0, vmec: '—', bonus: 'R$ 13,50', image_url: null },
  { name: 'Prata', cycles: 15, min_lines: 1, vmec: '100 %', bonus: 'R$ 40,50', image_url: null },
  { name: 'Ouro', cycles: 70, min_lines: 1, vmec: '100 %', bonus: 'R$ 189,00', image_url: null },
  { name: 'Safira', cycles: 150, min_lines: 2, vmec: '60 / 40', bonus: 'R$ 405,00', image_url: null },
  { name: 'Esmeralda', cycles: 300, min_lines: 2, vmec: '60 / 40', bonus: 'R$ 810,00', image_url: null },
  { name: 'Topázio', cycles: 500, min_lines: 2, vmec: '60 / 40', bonus: 'R$ 1.350,00', image_url: null },
  { name: 'Rubi', cycles: 750, min_lines: 3, vmec: '50 / 30 / 20', bonus: 'R$ 2.025,00', image_url: null },
  { name: 'Diamante', cycles: 1500, min_lines: 3, vmec: '50 / 30 / 20', bonus: 'R$ 4.050,00', image_url: null },
  { name: 'Duplo Diamante', cycles: 3000, min_lines: 4, vmec: '40 / 30 / 20 / 10', bonus: 'R$ 18.450,00', image_url: null },
  { name: 'Triplo Diamante', cycles: 5000, min_lines: 5, vmec: '35 / 25 / 20 / 10 / 10', bonus: 'R$ 36.450,00', image_url: null },
  { name: 'Diamante Red', cycles: 15000, min_lines: 6, vmec: '30 / 20 / 18 / 12 / 10 / 10', bonus: 'R$ 67.500,00', image_url: null },
  { name: 'Diamante Blue', cycles: 25000, min_lines: 6, vmec: '30 / 20 / 18 / 12 / 10 / 10', bonus: 'R$ 105.300,00', image_url: null },
  { name: 'Diamante Black', cycles: 50000, min_lines: 6, vmec: '30 / 20 / 18 / 12 / 10 / 10', bonus: 'R$ 135.000,00', image_url: null },
];

async function seed() {
  console.log('Checking career_levels table...');

  // Check if table exists and has data
  const { data: existing, error } = await supabase.from('career_levels').select('id').limit(1);

  if (error) {
    if (error.code === '42P01') {
      console.error('\n❌ ERRO CRÍTICO: A tabela "career_levels" não existe no Supabase.');
      console.error('Por favor, execute o seguinte SQL no Editor SQL do Supabase para criar a tabela:\n');
      console.log(`
CREATE TABLE IF NOT EXISTS public.career_levels (
    id bigint generated by default as identity primary key,
    name text not null,
    cycles integer default 0,
    min_lines integer default 0,
    vmec text,
    bonus text,
    image_url text,
    active boolean default true,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Habilitar RLS (opcional, mas recomendado)
ALTER TABLE public.career_levels ENABLE ROW LEVEL SECURITY;

-- Política de leitura pública (para consultores verem)
CREATE POLICY "Public read access" ON public.career_levels FOR SELECT USING (true);

-- Política de escrita apenas para admins (ajuste conforme suas roles)
CREATE POLICY "Admin write access" ON public.career_levels FOR ALL USING (true); 
-- (Nota: Para simplificar o seed, a politica acima permite tudo, idealmente restrinja para roles de admin)
        `);
    } else {
      console.error('Erro ao acessar tabela:', error);
    }
    return;
  }

  if (existing && existing.length > 0) {
    console.log('✅ A tabela career_levels já contém dados. Seed pulado.');
    return;
  }

  console.log('Inseminando dados iniciais na tabela career_levels...');
  const { error: insertError } = await supabase.from('career_levels').insert(initialCareerData);

  if (insertError) {
    console.error('Erro ao inserir dados:', insertError);
  } else {
    console.log('✅ Sucesso! 13 PINs inseridos na tabela career_levels.');
  }
}

seed();
