import { Client } from 'pg';

const POOLER_URL = 'postgresql://postgres.rptkhrboejbwexseikuo:Yannis784512%40@aws-0-sa-east-1.pooler.supabase.com:6543/postgres?pgbouncer=true';

const initialCareerData = [
    { name: 'Consultor', cycles: 0, min_lines: 0, vmec: '0', bonus: 'R$ 0,00', image_url: '', active: true },
    { name: 'VIP', cycles: 1, min_lines: 1, vmec: '1.000', bonus: 'R$ 50,00', image_url: '', active: true },
    { name: 'Bronze', cycles: 3, min_lines: 2, vmec: '3.000', bonus: 'R$ 150,00', image_url: '', active: true },
    { name: 'Prata', cycles: 6, min_lines: 2, vmec: '6.000', bonus: 'R$ 300,00', image_url: '', active: true },
    { name: 'Ouro', cycles: 9, min_lines: 3, vmec: '12.000', bonus: 'R$ 600,00', image_url: '', active: true },
    { name: 'Diamante', cycles: 12, min_lines: 4, vmec: '24.000', bonus: 'R$ 1.200,00', image_url: '', active: true },
];

async function fixCareerDB() {
    console.log('🔌 Conectando ao banco de dados (Direct)...');
    let client = new Client({
        host: 'db.rptkhrboejbwexseikuo.supabase.co',
        port: 5432,
        user: 'postgres',
        password: 'Yannis784512@',
        database: 'postgres',
        ssl: { rejectUnauthorized: false }
    });

    try {
        await client.connect();
        console.log('✅ Conectado!');

        console.log('🛠️ Recriando tabela career_levels...');
        await client.query(`DROP TABLE IF EXISTS public.career_levels CASCADE;`);
        await client.query(`
            CREATE TABLE public.career_levels (
                id bigint generated by default as identity primary key,
                name text not null,
                cycles integer default 0,
                min_lines integer default 0,
                vmec text,
                bonus text,
                image_url text,
                active boolean default true,
                created_at timestamp with time zone default timezone('utc'::text, now()) not null
            );
        `);
        console.log('✅ Tabela recriada.');

        console.log('🔒 Configurando RLS...');
        await client.query(`ALTER TABLE public.career_levels ENABLE ROW LEVEL SECURITY;`);
        await client.query(`CREATE POLICY "Public read access" ON public.career_levels FOR SELECT USING (true);`);
        await client.query(`CREATE POLICY "Admin write access" ON public.career_levels FOR ALL USING (true);`); // Simplified for now
        console.log('✅ RLS configurado.');

        console.log('🌱 Inserindo dados iniciais...');
        for (const pin of initialCareerData) {
            await client.query(`
                INSERT INTO public.career_levels (name, cycles, min_lines, vmec, bonus, image_url, active)
                VALUES ($1, $2, $3, $4, $5, $6, $7)
            `, [pin.name, pin.cycles, pin.min_lines, pin.vmec, pin.bonus, pin.image_url, pin.active]);
        }
        console.log('✅ Dados inseridos com sucesso!');

    } catch (err) {
        console.error('❌ Erro:', err);
    } finally {
        await client.end();
        console.log('🔌 Desconectado.');
    }
}

fixCareerDB();
