// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { ENV } from '@/config/env';

/**
 * Cliente Supabase configurado com variáveis de ambiente
 * 
 * ⚠️ SEGURANÇA:
 * - NUNCA exponha Service Keys no frontend
 * - Use apenas Publishable/Anon Keys
 * - Configurações sensíveis devem estar em .env (não commitadas)
 */
export const supabase = createClient<Database>(
  ENV.SUPABASE_URL,
  ENV.SUPABASE_ANON_KEY,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  }
);