#!/bin/bash

# ============================================================================
# RS SUPABASE - DBA DEPLOYMENT CHECKLIST
# ============================================================================
# Script auxiliar para lembrar o DBA dos passos necessários
# NÃO executa nada automaticamente - apenas imprime instruções
# ============================================================================

echo ""
echo "════════════════════════════════════════════════════════════════════════"
echo "  RS PRÓLIPSI - CHECKLIST DE DEPLOYMENT SUPABASE"
echo "════════════════════════════════════════════════════════════════════════"
echo ""
echo "📋 Este script é apenas um lembrete. Siga os passos manualmente."
echo ""
echo "────────────────────────────────────────────────────────────────────────"
echo "  PASSO 1: EXECUTAR MIGRATION NO SUPABASE"
echo "────────────────────────────────────────────────────────────────────────"
echo ""
echo "1. Acesse: https://app.supabase.com"
echo "2. Selecione o projeto RS Prólipsi"
echo "3. Vá em SQL Editor (menu lateral)"
echo "4. Copie TODO o conteúdo de:"
echo "   📄 supabase/migrations/rs-backend-sync-001.sql"
echo "5. Cole no editor e clique em RUN"
echo "6. Aguarde conclusão (~5-10 segundos)"
echo ""
echo "✅ Verificação:"
echo "   Execute no SQL Editor:"
echo ""
echo "   SELECT table_name"
echo "   FROM information_schema.tables"
echo "   WHERE table_schema = 'public'"
echo "   AND (table_name LIKE 'sigma_%' OR table_name IN ('logistics_orders', 'cycles'));"
echo ""
echo "   Resultado esperado: 7 linhas (tabelas)"
echo ""
echo "────────────────────────────────────────────────────────────────────────"
echo "  PASSO 2: EXECUTAR SEED NO SUPABASE"
echo "────────────────────────────────────────────────────────────────────────"
echo ""
echo "1. No mesmo SQL Editor, criar nova query"
echo "2. Copie TODO o conteúdo de:"
echo "   📄 supabase/seeds/001-sigma-default-config.sql"
echo "3. Cole no editor e clique em RUN"
echo "4. Observe os RAISE NOTICE no output (resumo de inserções)"
echo ""
echo "✅ Verificação:"
echo "   Execute no SQL Editor:"
echo ""
echo "   SELECT"
echo "       (SELECT COUNT(*) FROM sigma_settings) as settings,"
echo "       (SELECT COUNT(*) FROM sigma_depth_levels) as depth,"
echo "       (SELECT COUNT(*) FROM sigma_fidelity_levels) as fidelity,"
echo "       (SELECT COUNT(*) FROM sigma_top10_levels) as top10,"
echo "       (SELECT COUNT(*) FROM sigma_career_pins) as pins;"
echo ""
echo "   Resultado esperado: settings=1, depth=6, fidelity=6, top10=10, pins=13"
echo ""
echo "────────────────────────────────────────────────────────────────────────"
echo "  PASSO 3: GERAR TOKEN INTERNO"
echo "────────────────────────────────────────────────────────────────────────"
echo ""
echo "Execute no terminal local:"
echo ""
echo "   openssl rand -hex 32"
echo ""
echo "Copie o output (será usado como INTERNAL_API_TOKEN)"
echo ""
echo "────────────────────────────────────────────────────────────────────────"
echo "  PASSO 4: OBTER CREDENCIAIS SUPABASE"
echo "────────────────────────────────────────────────────────────────────────"
echo ""
echo "1. No Supabase Dashboard, vá em Settings → API"
echo "2. Copie:"
echo "   - Project URL → SUPABASE_URL"
echo "   - service_role (secret) → SUPABASE_SERVICE_KEY"
echo ""
echo "⚠️  NUNCA compartilhe ou commite SUPABASE_SERVICE_KEY"
echo ""
echo "────────────────────────────────────────────────────────────────────────"
echo "  PASSO 5: CRIAR ARQUIVOS .env"
echo "────────────────────────────────────────────────────────────────────────"
echo ""
echo "Copiar .env.example para .env em cada serviço:"
echo ""
echo "   cp apps/rs-api/.env.example apps/rs-api/.env"
echo "   cp apps/rs-core/.env.example apps/rs-core/.env"
echo "   cp apps/rs-logistica/.env.example apps/rs-logistica/.env"
echo ""
echo "Preencher variáveis:"
echo ""
echo "   apps/rs-api/.env:"
echo "     SUPABASE_URL=https://seu-projeto.supabase.co"
echo "     SUPABASE_SERVICE_KEY=eyJhbGciOiJI..."
echo "     INTERNAL_API_TOKEN=9a7f3c... (token gerado no passo 3)"
echo ""
echo "   apps/rs-core/.env:"
echo "     SUPABASE_URL=https://seu-projeto.supabase.co (MESMO do rs-api)"
echo "     SUPABASE_SERVICE_KEY=eyJhbGciOiJI... (MESMO do rs-api)"
echo "     INTERNAL_API_TOKEN=9a7f3c... (MESMO do rs-api)"
echo ""
echo "   apps/rs-logistica/.env:"
echo "     INTERNAL_API_TOKEN=9a7f3c... (MESMO dos outros)"
echo ""
echo "⚠️  CRÍTICO: INTERNAL_API_TOKEN deve ser EXATAMENTE IGUAL nos 3 serviços"
echo ""
echo "────────────────────────────────────────────────────────────────────────"
echo "  PASSO 6: EXECUTAR TESTES LOCAIS"
echo "────────────────────────────────────────────────────────────────────────"
echo ""
echo "Terminal 1 - Subir rs-api:"
echo "   cd apps/rs-api"
echo "   npm run dev"
echo ""
echo "Terminal 2 - Testar config flow:"
echo "   cd apps/rs-api"
echo "   npm run test:config-flow"
echo ""
echo "Terminal 3 - Testar getRule:"
echo "   cd apps/rs-core"
echo "   npm run test:getrule"
echo ""
echo "Terminal 4 - Verificar duplicados:"
echo "   cd apps/rs-api"
echo "   npm run test:db-duplicates"
echo ""
echo "✅ Resultados esperados:"
echo "   - test:config-flow: 'SUCCESS: Config was updated correctly!'"
echo "   - test:getrule: 'getRule would use DYNAMIC CONFIG from Supabase'"
echo "   - test:db-duplicates: 'No duplicate tables found'"
echo ""
echo "────────────────────────────────────────────────────────────────────────"
echo "  CHECKLIST FINAL"
echo "────────────────────────────────────────────────────────────────────────"
echo ""
echo "Banco de Dados:"
echo "  [ ] Migration executada sem erros"
echo "  [ ] Seed executado (36 registros)"
echo "  [ ] Query de verificação retorna 7 tabelas"
echo "  [ ] Query de verificação retorna 36 registros"
echo ""
echo "Variáveis de Ambiente:"
echo "  [ ] SUPABASE_URL configurada em rs-api e rs-core"
echo "  [ ] SUPABASE_SERVICE_KEY configurada em rs-api e rs-core"
echo "  [ ] INTERNAL_API_TOKEN igual em rs-api, rs-core, rs-logistica"
echo "  [ ] Arquivos .env NÃO commitados no Git"
echo ""
echo "Testes:"
echo "  [ ] test:config-flow → ✅ SUCCESS"
echo "  [ ] test:getrule → ✅ Value from database (não fallback)"
echo "  [ ] test:db-duplicates → ✅ No duplicates"
echo ""
echo "════════════════════════════════════════════════════════════════════════"
echo "  📚 DOCUMENTAÇÃO COMPLETA"
echo "════════════════════════════════════════════════════════════════════════"
echo ""
echo "Para instruções detalhadas, consulte:"
echo "   📄 docs/RS_SUPABASE_DBA_PLAYBOOK.md"
echo ""
echo "Para relatório de validação técnica:"
echo "   📄 docs/RS_DYNAMIC_CONFIG_NORMALIZATION_REPORT.md"
echo ""
echo "════════════════════════════════════════════════════════════════════════"
echo ""
