name: RS Reusable Deploy
on:
  workflow_call:
    inputs:
      remote_path: { required: true, type: string }
      artifact_path: { required: true, type: string }
      domain: { required: true, type: string }
      restart_cmd: { required: false, type: string, default: "" }
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via rsync
        uses: burnett01/rsync-deployments@v7.1
        with:
          switches: -avzr --delete
          path: ${{ inputs.artifact_path }}/
          remote_path: ${{ inputs.remote_path }}/
          remote_host: ${{ secrets.VPS_HOST }}
          remote_user: ${{ secrets.VPS_USER }}
          remote_key:  ${{ secrets.VPS_KEY }}
      - name: Restart service
        if: ${{ inputs.restart_cmd != '' }}
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          script: ${{ inputs.restart_cmd }}
